### ISSUE TITLE
Peril currently not working

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/peril-settings#8]
On the latest master (922580b8f71cc7c2d8f1d2a6caec668ae97b75d1) but I'm seeing this in logs:

```
2018-07-23T13:28:04.201839+00:00 app[web.1]: info: [runner] - Commenting, with results: 
2018-07-23T13:28:04.201857+00:00 app[web.1]: mds: 1
2018-07-23T13:28:04.201859+00:00 app[web.1]: messages: 0
2018-07-23T13:28:04.201860+00:00 app[web.1]: warns: 0
2018-07-23T13:28:04.201862+00:00 app[web.1]: fails: 0
2018-07-23T13:28:04.201863+00:00 app[web.1]:   
2018-07-23T13:28:04.277022+00:00 app[web.1]: error: Error:  TypeError: Cannot read property 'concat' of undefined
2018-07-23T13:28:04.277027+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:272:46)
2018-07-23T13:28:04.277029+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-07-23T13:28:04.277031+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-07-23T13:28:04.277033+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-07-23T13:28:04.277035+00:00 app[web.1]:     at <anonymous>
2018-07-23T13:28:04.277036+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-23T13:28:04.281657+00:00 app[web.1]: /app/out/peril.js:25
2018-07-23T13:28:04.281660+00:00 app[web.1]:         throw reason;
2018-07-23T13:28:04.281662+00:00 app[web.1]:         ^
2018-07-23T13:28:04.281664+00:00 app[web.1]: 
2018-07-23T13:28:04.281666+00:00 app[web.1]: TypeError: Cannot read property 'concat' of undefined
2018-07-23T13:28:04.281668+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:272:46)
2018-07-23T13:28:04.281669+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-07-23T13:28:04.281671+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-07-23T13:28:04.281672+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-07-23T13:28:04.281674+00:00 app[web.1]:     at <anonymous>
2018-07-23T13:28:04.281676+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-23T13:28:06.867972+00:00 app[web.1]: info:  
2018-07-23T13:28:06.876801+00:00 app[web.1]: info: ☢️  Starting up Peril
2018-07-23T13:28:06.878710+00:00 app[web.1]: info: ✓ Papertrail
2018-07-23T13:28:06.879108+00:00 app[web.1]: info: ✓ Clustering
2018-07-23T13:28:06.879300+00:00 app[web.1]: info: ✓ JSON Db at ashfurrow/peril-settings@settings-peril.json
2018-07-23T13:28:06.879486+00:00 app[web.1]: info: ✓ Server:
2018-07-23T13:28:06.879754+00:00 app[web.1]: info:   - Local: http://localhost:3801
2018-07-23T13:28:11.994200+00:00 app[web.1]: error: Error:  TypeError: Cannot read property 'scheduler' of null
2018-07-23T13:28:11.994218+00:00 app[web.1]:     at installations.forEach.installation (/app/out/scheduler/startScheduler.js:14:38)
2018-07-23T13:28:11.994220+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2018-07-23T13:28:11.994222+00:00 app[web.1]:     at Timeout.exports.runSchedule [as _onTimeout] (/app/out/scheduler/startScheduler.js:13:19)
2018-07-23T13:28:11.994224+00:00 app[web.1]:     at <anonymous>
2018-07-23T13:28:11.994225+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-23T13:28:11.997029+00:00 app[web.1]: /app/out/peril.js:25
2018-07-23T13:28:11.997032+00:00 app[web.1]:         throw reason;
2018-07-23T13:28:11.997034+00:00 app[web.1]:         ^
2018-07-23T13:28:11.997035+00:00 app[web.1]: 
2018-07-23T13:28:11.997037+00:00 app[web.1]: TypeError: Cannot read property 'scheduler' of null
2018-07-23T13:28:11.997039+00:00 app[web.1]:     at installations.forEach.installation (/app/out/scheduler/startScheduler.js:14:38)
2018-07-23T13:28:11.997040+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2018-07-23T13:28:11.997042+00:00 app[web.1]:     at Timeout.exports.runSchedule [as _onTimeout] (/app/out/scheduler/startScheduler.js:13:19)
2018-07-23T13:28:11.997043+00:00 app[web.1]:     at <anonymous>
2018-07-23T13:28:11.997045+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-23T13:28:14.905618+00:00 app[web.1]: info:  
```

Could be a config thing or something, will check after work.

**Comment by orta** [comment]
looks like somehow results.fails is coming back as null-y

<img width="994" alt="screen shot 2018-07-24 at 7 51 21 am" src="https://user-images.githubusercontent.com/49038/43136340-6764d312-8f16-11e8-91d7-23d940212781.png">

**Comment by orta** [comment]
Can you set `DEBUG` as `"*"` in your heroku env, and look to see if `Running platformResultsPreMapper` appears in the logs?

(sidenote, let me know if you see `"Not using the checks API for GitHub"` also)

**Comment by orta** [comment]
It should not run, basically.

**Comment by ashfurrow** [comment]
Hmm! Interesting. Here're the logs, it's just this repeated over and over:

```
2018-07-24T14:01:56.127361+00:00 heroku[web.1]: Starting process with command `npm start`
2018-07-24T14:01:58.319889+00:00 app[web.1]: 
2018-07-24T14:01:58.319926+00:00 app[web.1]: > peril@0.0.1 start /app
2018-07-24T14:01:58.319928+00:00 app[web.1]: > node out/index.js
2018-07-24T14:01:58.319930+00:00 app[web.1]: 
2018-07-24T14:02:02.251172+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "x-powered-by" to true
2018-07-24T14:02:02.252725+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "etag" to 'weak'
2018-07-24T14:02:02.253423+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "etag fn" to [Function: generateETag]
2018-07-24T14:02:02.253650+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "env" to 'production'
2018-07-24T14:02:02.253863+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "query parser" to 'extended'
2018-07-24T14:02:02.254325+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
2018-07-24T14:02:02.254692+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "subdomain offset" to 2
2018-07-24T14:02:02.254910+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "trust proxy" to false
2018-07-24T14:02:02.255623+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "trust proxy fn" to [Function: trustNone]
2018-07-24T14:02:02.255753+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application booting in production mode
2018-07-24T14:02:02.255987+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "view" to [Function: View]
2018-07-24T14:02:02.256154+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "views" to '/app/views'
2018-07-24T14:02:02.256288+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "jsonp callback name" to 'callback'
2018-07-24T14:02:02.256445+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "view cache" to true
2018-07-24T14:02:02.256619+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:application set "port" to '10533'
2018-07-24T14:02:02.258377+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router use '/' query
2018-07-24T14:02:02.258698+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.259868+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router use '/' expressInit
2018-07-24T14:02:02.260031+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.260456+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router use '/' <anonymous>
2018-07-24T14:02:02.260569+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.261594+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router use '/' jsonParser
2018-07-24T14:02:02.261746+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.262368+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router use '/' serveStatic
2018-07-24T14:02:02.262483+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.262880+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:route new '/webhook'
2018-07-24T14:02:02.263015+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/webhook'
2018-07-24T14:02:02.263382+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:route post '/webhook'
2018-07-24T14:02:02.263495+00:00 app[web.1]: Tue, 24 Jul 2018 14:02:02 GMT express:router:layer new '/'
2018-07-24T14:02:02.271662+00:00 app[web.1]: info:  
2018-07-24T14:02:02.280231+00:00 app[web.1]: info: ☢️  Starting up Peril
2018-07-24T14:02:02.281892+00:00 app[web.1]: info: ✓ Papertrail
2018-07-24T14:02:02.282230+00:00 app[web.1]: info: ✓ Clustering
2018-07-24T14:02:02.282405+00:00 app[web.1]: info: ✓ JSON Db at ashfurrow/peril-settings@settings-peril.json
2018-07-24T14:02:02.282553+00:00 app[web.1]: info: ✓ Server:
2018-07-24T14:02:02.282792+00:00 app[web.1]: info:   - Local: http://localhost:10533
2018-07-24T14:02:03.741325+00:00 heroku[web.1]: State changed from starting to up
2018-07-24T14:02:07.310564+00:00 app[web.1]: error: Error:  TypeError: Cannot read property 'scheduler' of null
2018-07-24T14:02:07.310609+00:00 app[web.1]:     at installations.forEach.installation (/app/out/scheduler/startScheduler.js:14:38)
2018-07-24T14:02:07.310612+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2018-07-24T14:02:07.310614+00:00 app[web.1]:     at Timeout.exports.runSchedule [as _onTimeout] (/app/out/scheduler/startScheduler.js:13:19)
2018-07-24T14:02:07.310616+00:00 app[web.1]:     at <anonymous>
2018-07-24T14:02:07.310618+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-24T14:02:07.311927+00:00 app[web.1]: /app/out/peril.js:25
2018-07-24T14:02:07.311929+00:00 app[web.1]:         throw reason;
2018-07-24T14:02:07.311931+00:00 app[web.1]:         ^
2018-07-24T14:02:07.311932+00:00 app[web.1]: 
2018-07-24T14:02:07.311936+00:00 app[web.1]: TypeError: Cannot read property 'scheduler' of null
2018-07-24T14:02:07.311938+00:00 app[web.1]:     at installations.forEach.installation (/app/out/scheduler/startScheduler.js:14:38)
2018-07-24T14:02:07.311940+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2018-07-24T14:02:07.311941+00:00 app[web.1]:     at Timeout.exports.runSchedule [as _onTimeout] (/app/out/scheduler/startScheduler.js:13:19)
2018-07-24T14:02:07.311943+00:00 app[web.1]:     at <anonymous>
2018-07-24T14:02:07.311945+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
```

I didn't get a chance to look last night, I'll try again tonight.

**Comment by orta** [comment]
https://github.com/danger/peril/commit/7fcc286502f52a1b48cb422b79e2aa5bace8a4b0 might fix that

**Comment by ashfurrow** [comment]
Mmmm, progress! Peril starts up but is back to not commenting due to a bad `concat`. 

```
2018-07-25T13:35:06.683827+00:00 app[web.1]: info:  
2018-07-25T13:35:06.684018+00:00 app[web.1]: info: ## issues.opened on unknown on ashfurrow/test-repo
2018-07-25T13:35:06.684269+00:00 app[web.1]: info:    1 run needed: rules/all-issues.ts
2018-07-25T13:35:06.902268+00:00 app[web.1]: 2018-07-25T13:35:06.902Z danger:transpiler:setup Does not have Babel 7 TypeScript set up
2018-07-25T13:35:07.543009+00:00 app[web.1]: 2018-07-25T13:35:07.542Z octokit:rest REQUEST: { timeout: 0,
2018-07-25T13:35:07.543026+00:00 app[web.1]:   agent: undefined,
2018-07-25T13:35:07.543028+00:00 app[web.1]:   method: 'get',
2018-07-25T13:35:07.543030+00:00 app[web.1]:   url: 'https://api.github.com/repos/ashfurrow/test-repo',
2018-07-25T13:35:07.543032+00:00 app[web.1]:   headers: 
2018-07-25T13:35:07.543034+00:00 app[web.1]:    { accept: 'application/vnd.github.drax-preview+json,application/vnd.github.machine-man-preview+json',
2018-07-25T13:35:07.543036+00:00 app[web.1]:      'user-agent': 'octokit/rest.js v15.6.1',
2018-07-25T13:35:07.543038+00:00 app[web.1]:      authorization: 'Bearer v1.A_BUNCH_OF_DIGITS' },
2018-07-25T13:35:07.543039+00:00 app[web.1]:   body: undefined }
2018-07-25T13:35:07.625198+00:00 app[web.1]: info: [runner] - Commenting, with results: 
2018-07-25T13:35:07.625203+00:00 app[web.1]: mds: 1
2018-07-25T13:35:07.625204+00:00 app[web.1]: messages: 0
2018-07-25T13:35:07.625206+00:00 app[web.1]: warns: 0
2018-07-25T13:35:07.625207+00:00 app[web.1]: fails: 0
2018-07-25T13:35:07.625209+00:00 app[web.1]:   
2018-07-25T13:35:07.650543+00:00 app[web.1]: 2018-07-25T13:35:07.650Z danger:executor Got Results back, current settings { dangerID: 'peril',
2018-07-25T13:35:07.650547+00:00 app[web.1]:   jsonOnly: false,
2018-07-25T13:35:07.650548+00:00 app[web.1]:   stdoutOnly: false,
2018-07-25T13:35:07.650550+00:00 app[web.1]:   verbose: false,
2018-07-25T13:35:07.650552+00:00 app[web.1]:   accessTokenIsGitHubApp: true }
2018-07-25T13:35:07.651967+00:00 app[web.1]: 2018-07-25T13:35:07.651Z danger:executor Running platformResultsPreMapper
2018-07-25T13:35:07.658021+00:00 app[web.1]: error: Error:  TypeError: Cannot read property 'concat' of undefined
2018-07-25T13:35:07.658024+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:272:46)
2018-07-25T13:35:07.658025+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-07-25T13:35:07.658026+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-07-25T13:35:07.658028+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-07-25T13:35:07.658029+00:00 app[web.1]:     at <anonymous>
2018-07-25T13:35:07.658030+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
2018-07-25T13:35:07.658848+00:00 app[web.1]: /app/out/peril.js:25
2018-07-25T13:35:07.658855+00:00 app[web.1]:         throw reason;
2018-07-25T13:35:07.658857+00:00 app[web.1]:         ^
2018-07-25T13:35:07.658859+00:00 app[web.1]: 
2018-07-25T13:35:07.658861+00:00 app[web.1]: TypeError: Cannot read property 'concat' of undefined
2018-07-25T13:35:07.658863+00:00 app[web.1]:     at Executor.<anonymous> (/app/node_modules/danger/distribution/runner/Executor.js:272:46)
2018-07-25T13:35:07.658865+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/Executor.js:32:23)
2018-07-25T13:35:07.658867+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/Executor.js:13:53)
2018-07-25T13:35:07.658868+00:00 app[web.1]:     at fulfilled (/app/node_modules/danger/distribution/runner/Executor.js:4:58)
2018-07-25T13:35:07.658870+00:00 app[web.1]:     at <anonymous>
2018-07-25T13:35:07.658872+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by orta** [comment]
It's running the pre-mapper

```
2018-07-25T13:35:07.651967+00:00 app[web.1]: 2018-07-25T13:35:07.651Z danger:executor Running platformResultsPreMapper
```

When I think it probably shouldn't unsure, will have a think

**Comment by ashfurrow** [comment]
Got these additional details getting logged out:

```
2018-07-31T15:38:19.396229+00:00 app[web.1]: 2018-07-31T15:38:19.395Z danger:executor Running platformResultsPreMapper: () => github ? github.platformResultsPreMapper && github.platformResultsPreMapper.bind(github) : nullFunc
2018-07-31T15:38:19.401366+00:00 app[web.1]: 2018-07-31T15:38:19.401Z danger:executor Received results from platformResultsPreMapper: function () { [native code] }
```

Looks like the results are a function? I'll take a look later.

**Comment by ashfurrow** [comment]
Updated to the latest settings, looks like `platformResultsPreMapper` is returning a function rather than an object. Any tips? I'll take a deeper look...
